# generate a docker-compose file that runs rabbitmq, mongodb, minio, with recommended settings. username should be "unifolding" and password should be "unifolding"
version: '3.7'
services:
  mongodb:
    image: mongo:6.0.6
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: unifolding
      MONGO_INITDB_ROOT_PASSWORD: unifolding
    volumes:
      - ./data/mongodb:/data/db

  minio:
    image: minio/minio
    hostname: minio
    ports:
     - 9000:9000 # api port
     - 9001:9001 # console port
    environment:
      MINIO_ROOT_USER: unifolding # username of the management console
      MINIO_ROOT_PASSWORD: unifolding # password of the management console, at least 8 characters
    volumes:
      - ./data/minio.data:/data # map the data directory under the current directory to the /data directory in the container
      # - ./config:/root/.minio/ # map the configuration directory
    command: server --console-address ':9001' /data # assign the /data directory in the container
    privileged: true
    restart: always

  mongo-express:
    image: mongo-express
    hostname: mongo-express
    restart: always
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_URL=mongodb://unifolding:unifolding@mongodb:27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - "8081:8081"

  backend:
    image: davidliyutong/unifolding-backend:latest
    hostname: backend
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - UNIFOLDING_DB_HOST=mongodb
      - UNIFOLDING_APP_NUMREPLICAS=1
      - UNIFOLDING_OSS_HOST=minio
    ports:
      - "8080:8080"

networks:
  default:
    external: true
    name: unifolding