defaults:
  - train_supervised_base
  - _self_

datamodule:
  h5_path: /mnt/homes/wendi/data/DeformPAM/vr_imitation_flattening-folding-short_v7_dataset/Tshirt/data.h5

logger:
  experiment_name: Tshirt-short-action14-dataset-v7_hybrid_supervised_vr
