app:
  numReplicas: 1
api:
  port: 8080
  host: '0.0.0.0'
db:
  host: mongodb.example.com
  port: 27017
  database: unifolding
  username: unifolding
  password: unifolding
mq:
  host: rabbitmq.example.com
  port: 5672
  username: unifolding
  password: unifolding
  queue: unifolding
  exchange: ''
  routingKey: unifolding
oss:
  host: oss.example.com
  port: 9000
  tls: false
  accessKey: unifolding
  secretKey: unifolding
  bucket: unifolding