api:
  url: http://api.example.com:8080
oss:
  host: oss.example.com
  port: 9000
  tls: false
  accessKey: unifolding
  secretKey: unifolding
  bucket: unifolding
  endpoint: oss.example.com
  path_style: true