defaults:
  - experiment_finetune_base@_here_
  - ../supervised_experiment/experiment_supervised_tshirt_short.yaml@_here_
  - camera_param: mechmind_camera
  - _self_

inference:
  args:
    fling_override: False
    nearest_pick_override: True
    model:
      manually_select_diffusion_action_pair_for_inference: False

experiment:
  compat:
    camera:
      camera_param: ${camera_param}