defaults:
  - train_finetune_base
  - ../supervised_experiment/train_supervised_tshirt_short_real.yaml@_here_
  - _self_

runtime_datamodule:
  data_type: new_pipeline_finetune
  batch_size: 28

model:
  loss_diffusion_finetune_weight: 1.0
  finetune_loss_type: dpo # dpo, cpl
  dpo_beta: 100
  cpl_lambda: 1.0
  init_lr: 1e-5
  use_sft_for_equal_samples: False
  loss_diffusion_finetune_sft_euqal_weight: 1.0
  use_sft_for_gt_data: False
  loss_diffusion_finetune_sft_weight: 1.0

trainer_adjustment:
  use_adaptive_episode: False